### PR TITLE
Fix data type compatibility remarks

### PR DESCRIPTION
**Pull request by marcosqlbi**

### CODE REVIEW

**Review by Minewiskan — COMMENTED** [review]
Did you test this with a single data type? Logical values, text, and dates should return an error. If there is a mix of data types, blanks, logical values, dates, and text should be skipped, but any numeric values are counted.

**Comment by marcosqlbi** [comment]
When you use a single column as an argument, that column has a single data type. Currently, you cannot have variants as a data type in a Tabular model, which is the case in Excel. Thus, technically you cannot have a mix of data types.

**Comment by Minewiskan** [comment]
You are correct about variants with MEDIAN. However, "Logical values are converted to numbers." is not correct. logical values, along with text and dates return an error. My suggestion is 'Only the numbers in the column are counted. Blanks are ignored. Logical values, dates, and text are not supported.'

**Comment by marcosqlbi** [comment]
You're right - your suggestions work well, let me know if I should create another pull request or you will apply the fix directly.
Thanks!

**Comment by Minewiskan** [comment]
@marcosqlbi - Thanks for your contribution. The change now appears live on the en-us version of the DAX Reference. Localized versions of the reference are typically updated within the following 30 days.

**Pull request merged**
