### PR TITLE
M Language Spec Type Corrections

### PR DESCRIPTION
**Pull request by bgribaudo**
Primarily addresses the issues reported in https://github.com/MicrosoftDocs/powerquery-docs/issues/37

### CODE REVIEW

**Comment by JasonWHowell** [comment]
Thanks for the help @bgribaudo 
#assign:DougKlopfenstein for review with the product team.

**Comment by JasonWHowell** [comment]
Close / open to trigger the bot to refresh tags. #please-close

**Comment by JasonWHowell** [comment]
#please-open

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by DougKlopfenstein** [comment]
Reviewed by Curt.
#sign-off

**Pull request merged**
