### PR TITLE
Update summarizecolumns-function-dax.md

### PR DESCRIPTION
**Pull request by yichai-msft**
CalculateTable(
    SUMMARIZE(
        'Reseller Sales',
        [ResellerKey],
        [ProductKey]
    ),
    Treatas({(229)}, 'Product'[Product Key])
)

### CODE REVIEW

**Comment by jeroenterheerdt** [comment]
looks good!

**Comment by jeroenterheerdt** [comment]
#sign-off

**Comment by jeroenterheerdt** [comment]
@kfollis this can be merged anytime

**Comment by Court72** [comment]
@kfollis

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by kfollis** [comment]
#sign-off

**Pull request merged**
