### PR TITLE
Update treatas-function-dax.md

### PR DESCRIPTION
**Pull request by regurgitate**
sentence structure corrected, DAX formatting changed

### CODE REVIEW

**Comment by Court72** [comment]
@kfollis

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by kfollis** [comment]
@jeroenterheerdt - the grammatical change is valid, but I'm unable to verify the syntax change. Can you please review?

**Comment by jeroenterheerdt** [comment]
looks good to me, I don't believe the actual syntax has changed, it's just the layouting.

**Comment by kfollis** [comment]
[like]  Kate Follis reacted to your message:
________________________________

**Comment by kfollis** [comment]
#sign-off

**Pull request merged**
