### PR TITLE
Remove unnecessary parenthesis

### PR DESCRIPTION
**Pull request by rpln**

### CODE REVIEW

**Comment by Court72** [comment]
@kfollis 

Can you review the proposed changes or assign this PR to the correct author? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by peter-myers** [comment]
I agree with this change. I don't have sign off ability for this repo.

**Comment by kfollis** [comment]
#sign-off

**Comment by peter-myers** [comment]
Let me try... #sign-off

**Comment by kfollis** [comment]
@peter-myers I will move this commit to the private repo and sign-off from there.

**Comment by Jak-MS** [comment]
@kfollis - we'll review this shortly. looks like PRMerger isn't adding labels in this repo, but we monitor it.

**Comment by kfollis** [comment]
thanks, @Jak-MS!

**Pull request merged**
