### PR TITLE
Update calendarauto-function-dax.md

### PR DESCRIPTION
**Pull request by EnzoPavez**
Change contiguous to continuous

### CODE REVIEW

**Review by kfollis — APPROVED** [review]

**Comment by kfollis** [comment]
@EnzoPavez - please let me know if you're ready to move this to publishing. Thanks for the contribution!

**Comment by kfollis** [comment]
@jeroenterheerdt - can you please validate this change? I will move to publishing with your approval

**Comment by jeroenterheerdt** [comment]
@kfollis the original is fine by me. contiguous is the word that describes the requirements, the same as the continuous by the way. I see no need to make changes.

**Comment by kfollis** [comment]
#please-close

**Comment by kfollis** [comment]
[like]  Kate Follis reacted to your message:
________________________________

**Pull request closed without merging**
