### PR TITLE
Update to include COLUMN and TABLE with DEFINE

### PR DESCRIPTION
**Pull request by AKomonen**
Update documentation to include the possibility to define COLUMN and TABLE entities in a DEFINE statement.

### CODE REVIEW

**Comment by JasonWHowell** [comment]
@Minewiskan please review this substantive change to DAX language reference.

**Comment by JasonWHowell** [comment]
Close / open to get build validation to run.

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[ed0c517](https://github.com/AKomonen/query-docs/commits/ed0c517c9d5c3165daf5cb6b8dd1cb1437fd3dd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[query-languages/dax/dax-queries.md](https://github.com/AKomonen/query-docs/blob/patch-1/query-languages/dax/dax-queries.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/68682a47-e00a-3f02-ceb0-b5902342f7b4/202207300055446013-7/BuildReport?accessString=254f993b83328b0ac717718149ab75344efee00c569cd8414a2fcc1c5cfc0cfb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/68682a47-e00a-3f02-ceb0-b5902342f7b4?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[ed0c517](https://github.com/AKomonen/query-docs/commits/ed0c517c9d5c3165daf5cb6b8dd1cb1437fd3dd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[query-languages/dax/dax-queries.md](https://github.com/AKomonen/query-docs/blob/patch-1/query-languages/dax/dax-queries.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/68682a47-e00a-3f02-ceb0-b5902342f7b4/202207300055570729-7/BuildReport?accessString=fd1953a9768d2ae0390557445a3f0f2c9c3d90188b6f090535f89ed8cd246838).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/68682a47-e00a-3f02-ceb0-b5902342f7b4?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Minewiskan** [comment]
@AKomonen - Thanks for your contribution. This change, however, refers to features/functionality that are currently in preview and not yet complete. When complete, we'll update the article to reflect new functionality. We may re-open this commit at that time.

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[ed0c517](https://github.com/AKomonen/query-docs/commits/ed0c517c9d5c3165daf5cb6b8dd1cb1437fd3dd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[query-languages/dax/dax-queries.md](https://github.com/AKomonen/query-docs/blob/patch-1/query-languages/dax/dax-queries.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/68682a47-e00a-3f02-ceb0-b5902342f7b4/202208042045139780-7/BuildReport?accessString=ec179fe6c2b708358aeef46413b10aaa5a4ad21f8a7928dc274aa3f70e7e17a5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/68682a47-e00a-3f02-ceb0-b5902342f7b4?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by AKomonen** [comment]
I'm not sure which of the features/functionalities are in preview but basically I'm just suggesting you update the article to be in sync with the article https://docs.microsoft.com/en-us/dax/define-statement-dax where entities COLUMN and TABLE within a DEFINE statement are already included.

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[ed0c517](https://github.com/AKomonen/query-docs/commits/ed0c517c9d5c3165daf5cb6b8dd1cb1437fd3dd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[query-languages/dax/dax-queries.md](https://github.com/AKomonen/query-docs/blob/patch-1/query-languages/dax/dax-queries.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/68682a47-e00a-3f02-ceb0-b5902342f7b4/202208051646576635-7/BuildReport?accessString=d957fb9cfa7183221a38ee6d414186bebfa7986a033e0c9b3f0cc72e8dd49159).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/68682a47-e00a-3f02-ceb0-b5902342f7b4?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Minewiskan** [comment]
#in-progress

**Comment by Minewiskan** [comment]
> I'm not sure which of the features/functionalities are in preview but basically I'm just suggesting you update the article to be in sync with the article https://docs.microsoft.com/en-us/dax/define-statement-dax where entities COLUMN and TABLE within a DEFINE statement are already included.

@AKomonen - We're doing some more significant re-write of this article. It will include COLUMN and TABLE, however, there will be a Caution note stating that these functions are meant for internal use and not recommended for user scoped queries. We'll merge your PR just prior to that update. The other statement articles, DEFINE in particular, will also get an update.

**Pull request merged**
