### PR TITLE
Update new-dax-functions.md

### PR DESCRIPTION
**Pull request by MattAlington**
The release date was wrong.  It should be July 2022, not 2021

### CODE REVIEW

**Comment by MattAlington** [comment]
I actually have no idea how github works, if I have done this correctly, or otherwise.  I would appreciate if anyone seeing this lets me know if I did it right.

**Comment by JasonWHowell** [comment]
@Minewiskan please review this DAX change. Seems fine to me.

**Comment by JasonWHowell** [comment]
Close/Open to get build validation to run.

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[d399b13](https://github.com/MattAlington/query-docs/commits/d399b13cb9ea364be6e7c2649261accf5d1b8678)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[query-languages/dax/new-dax-functions.md](https://github.com/MattAlington/query-docs/blob/patch-1/query-languages/dax/new-dax-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/68682a47-e00a-3f02-ceb0-b5902342f7b4/202207300056539849-6/BuildReport?accessString=64d29209df2b119d7efa88c8841ceba684e8bb998d17beeae814fc7eaf2a44bc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/68682a47-e00a-3f02-ceb0-b5902342f7b4?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[d399b13](https://github.com/MattAlington/query-docs/commits/d399b13cb9ea364be6e7c2649261accf5d1b8678)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[query-languages/dax/new-dax-functions.md](https://github.com/MattAlington/query-docs/blob/patch-1/query-languages/dax/new-dax-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/68682a47-e00a-3f02-ceb0-b5902342f7b4/202207300207496438-6/BuildReport?accessString=cc952500134bf4fefeb5e9cac123a4b59df628b56908617433495d6dcc2d5dae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/68682a47-e00a-3f02-ceb0-b5902342f7b4?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[d399b13](https://github.com/MattAlington/query-docs/commits/d399b13cb9ea364be6e7c2649261accf5d1b8678)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[query-languages/dax/new-dax-functions.md](https://github.com/MattAlington/query-docs/blob/patch-1/query-languages/dax/new-dax-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/68682a47-e00a-3f02-ceb0-b5902342f7b4/202207300208011084-6/BuildReport?accessString=0382f2f06fc42bfdf4f03d2ec814bc6f2aa2b2fb5464abba6362e5c7a4832a9e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/68682a47-e00a-3f02-ceb0-b5902342f7b4?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[d399b13](https://github.com/MattAlington/query-docs/commits/d399b13cb9ea364be6e7c2649261accf5d1b8678)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[query-languages/dax/new-dax-functions.md](https://github.com/MattAlington/query-docs/blob/patch-1/query-languages/dax/new-dax-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/68682a47-e00a-3f02-ceb0-b5902342f7b4/202207300057056735-6/BuildReport?accessString=2a30ddc429ce867070e957137aaaf831c21e1151e6cc0eeda67389784d58d310).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/68682a47-e00a-3f02-ceb0-b5902342f7b4?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[d399b13](https://github.com/MattAlington/query-docs/commits/d399b13cb9ea364be6e7c2649261accf5d1b8678)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[query-languages/dax/new-dax-functions.md](https://github.com/MattAlington/query-docs/blob/patch-1/query-languages/dax/new-dax-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/68682a47-e00a-3f02-ceb0-b5902342f7b4/202208041804398181-6/BuildReport?accessString=9118c80d4e3d04c1ce97b4ab3886163c414e24958bafe4621ab4a4e6374bc677).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/68682a47-e00a-3f02-ceb0-b5902342f7b4?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
